about:
  home: https://github.com/avengerpb/vcf2hapmap_conda
  license_file: LICENSE
  summary: Convert VCF file to Hapmap file

build:
  detect_binary_files_with_prefix: true
  number: 0
  skip: False

requirements:
  run:
    - perl

package:
  name: vcf2hapmap
  version: 1.0.0

source:
  git_url: https://github.com/avengerpb/vcf2hapmap_conda
  MD5: 9ddfa9948580ad688014aa929161ff2d

