about:
  home: https://github.com/avengerpb/vcf2hapmap_conda
  license: Artistic-2.0
  summary: Convert VCF file to Hapmap file

build:
  detect_binary_files_with_prefix: true
  number: 0
  skip: False

requirements:
  run:
    - perl

package:
  name: vcf2hapmap
  version: 1.0.0

test:
  commands:
    - vcf2FastaAndHapmap.sh test.vcf out

