about:
  home: https://github.com/avengerpb/vcf2hapmap_conda
  license_file: LICENSE
  summary: Convert VCF file to Hapmap file

build:
  detect_binary_files_with_prefix: true
  number: 0
  skip: False

requirements:
  run:
    - perl

package:
  name: vcf2hapmap
  version: 1.0.0

source:
  url: https://github.com/avengerpb/vcf2hapmap_conda/archive/1.0.tar.gz
  MD5: 593110d90124acbaea50832261dbcc36

test:
  commands:
    - vcf2hapmap.sh

